algashop:
  api-url: ${aws.params.api.url}
  auth-with-alga-security-path: /oauth2/authorization/oidc
  payment-provider-public-key: ${aws.params.payment.public-key}
  payment-provider-credit-card-token-url: ${aws.params.payment.url}
  authorization-server-url: ${aws.shared.auth.issuer-uri}

spring:
  config:
    import:
      - aws-parameterstore:/config/production/shared/?prefix=aws.shared.
      - aws-parameterstore:/config/production/ecommerce-web/?prefix=aws.params.
  datasource:
    url: ${aws.params.postgres.host}
    username: ${aws.params.postgres.username}
    driver-class-name: ${aws.params.postgres.driver}
  data:
    redis:
      host: ${aws.shared.redis.host}
      port: ${aws.shared.redis.port}
      password: ${aws.shared.redis.password}
      database: ${aws.shared.redis.slot}
      ssl:
        enabled: true
  cloud:
     aws:
      region:
        static: ${AWS_REGION:us-east-2}
      credentials:
        access-key: ${AWS_ACCESS_KEY_ID}
        secret-key: ${AWS_SECRET_ACCESS_KEY}
      secretsmanager:
        reload:
          period: 30s
      parameterstore:
        reload:
          period: 30s
  security:
    oauth2:
      client:
        registration:
          oidc:
            provider: algashop-auth
            client-id: ${aws.params.oauth2.oidc.client-id}
            client-secret: ${aws.params.oauth2.oidc.client-secret}
            redirect-uri: ${aws.params.oauth2.oidc.redirect-url}
            authorization-grant-type: authorization_code
            scope:
              - "openid"
              - "read"
              - "write"
            client-name: algashop-integration-client
          backend:
            provider: algashop-auth
            client-id: ${aws.params.oauth2.backend.client-id}
            client-secret: ${aws.params.oauth2.backend.client-secret}
            authorization-grant-type: client_credentials
            scope:
              - "read"
              - "customers:create"
            client-name: algashop-products-integration-client
        provider:
          algashop-auth:
            issuer-uri: ${aws.shared.auth.issuer-uri}